### ISSUE TITLE
[Request] Accept, Reject friend-requests?

### ISSUE THREAD

**Issue by summers314** [amaboura/socialbase#2]
Hey. Extremely helpful library.

Does the library support friend requests and the necessary checks required when I'm sending a friend request? Like:
-Check if username is valid
-Check if users are not already friends etc.

Or any plans of building that in the future?

http://stackoverflow.com/questions/41198113/sending-friend-request-using-firebase-on-android

Thanks :)

**Comment by amaboura** [comment]
Hey there, 

Using the current schema, you still can check if the username is valid, if you encrypt a username using a basic hash function (eg: sha224), then you can use it as key for each user child added to the users node, which means using the same hash function later, you will be able to verify the username availability.

To check if the user is already a friend connection, you just need to check if both users follow each others.

Friend request feature is interesting to add, however you can still achieve this, by creating a custom event each time a user send a request, which you can tag by, for example, "request_sent", and then do the same thing on the receiver side, and tag it with "request_received", you subscribe on firebase nodes updates on both sender and receiver sides, which then you can handle through the client app (eg: accept friend request / notify the sender)

I hope this helps.

Thanks

**Comment by summers314** [comment]
Cool. Ill check it out. Thanks :)
